WXR\EventBundle\Entity\BaseEvent:
    type: mappedSuperclass
    fields:
        enabled:
            type: boolean
        title:
            length: 255
        content:
            type: text
        excerpt:
            type: text
            nullable: true
        startAt:
            column: start_at
            type: datetime
        endAt:
            column: end_at
            type: datetime
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
    lifecycleCallbacks:
        preUpdate: [ onPreUpdate ]
