WXR\EventBundle\Entity\BaseEvent:
    type: mappedSuperclass
    fields:
        enabled:
            type: boolean
        title:
            length: 255
        description:
            type: text
        excerpt:
            type: text
            nullable: true
        startsAt:
            column: starts_at
            type: datetime
        endsAt:
            column: ends_at
            type: datetime
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
    lifecycleCallbacks:
        preUpdate: [ onPreUpdate ]
