parameters:

    wxr_event.event.class: Application\WXR\EventBundle\Entity\Event
    wxr_event.category.class: Application\WXR\EventBundle\Entity\Category
    wxr_event.tag.class: Application\WXR\EventBundle\Entity\Tag

services:

    wxr_event.event.manager.default:
        class: WXR\EventBundle\Entity\EventManager
        arguments: [@doctrine.orm.entity_manager, %wxr_event.event.class%]

    wxr_event.event.admin:
        class: %wxr_event.event.admin.class%
        arguments: [ ~, %wxr_event.event.class%, %wxr_event.event.admin.controller% ]
        calls:
            - [ setTranslationDomain, [ %wxr_event.translation_domain% ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: wxr_event
                label: events
                label_catalogue: %wxr_event.translation_domain%
                label_translator_strategy: sonata.admin.label.strategy.underscore

    wxr_event.category.manager.default:
        class: WXR\EventBundle\Entity\CategoryManager
        arguments: [@doctrine.orm.entity_manager, %wxr_event.category.class%, %wxr_event.event.class%]

    wxr_event.category.admin:
        class: %wxr_event.category.admin.class%
        arguments: [ ~, %wxr_event.category.class%, %wxr_event.category.admin.controller% ]
        calls:
            - [ setTranslationDomain, [ %wxr_event.translation_domain% ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: wxr_event
                label: categories
                label_catalogue: %wxr_event.translation_domain%
                label_translator_strategy: sonata.admin.label.strategy.underscore

    wxr_event.tag.manager.default:
        class: WXR\EventBundle\Entity\TagManager
        arguments: [@doctrine.orm.entity_manager, %wxr_event.tag.class%]

    wxr_event.tag.admin:
        class: %wxr_event.tag.admin.class%
        arguments: [ ~, %wxr_event.tag.class%, %wxr_event.tag.admin.controller% ]
        calls:
            - [ setTranslationDomain, [ %wxr_event.translation_domain% ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: wxr_event
                label: tags
                label_catalogue: %wxr_event.translation_domain%
                label_translator_strategy: sonata.admin.label.strategy.underscore
