parameters:

services:

    wxr_event.event.manager.default:
        class: WXR\EventBundle\Entity\EventManager
        arguments: [@doctrine.orm.entity_manager, %wxr_event.event.class%]
    wxr_event.event.admin.default:
        class: WXR\EventBundle\Admin\Entity\EventAdmin
        arguments: [ ~, %wxr_event.event.class%, SonataAdminBundle:CRUD ]
        calls:
            - [ setTranslationDomain, [ %wxr_event.translation_domain% ] ]
        tags:
            -
                name: sonata.admin.disabled
                manager_type: orm
                group: wxr_event
                label: events
                label_catalogue: %wxr_event.translation_domain%
                label_translator_strategy: sonata.admin.label.strategy.underscore

    wxr_event.category.manager.default:
        class: WXR\EventBundle\Entity\CategoryManager
        arguments: [@doctrine.orm.entity_manager, %wxr_event.category.class%, %wxr_event.event.class%]
    wxr_event.category.admin.default:
        class: WXR\EventBundle\Admin\Entity\CategoryAdmin
        arguments: [ ~, %wxr_event.category.class%, SonataAdminBundle:CRUD ]
        calls:
            - [ setTranslationDomain, [ %wxr_event.translation_domain% ] ]
        tags:
            -
                name: sonata.admin.disabled
                manager_type: orm
                group: wxr_event
                label: categories
                label_catalogue: %wxr_event.translation_domain%
                label_translator_strategy: sonata.admin.label.strategy.underscore

    wxr_event.tag.manager.default:
        class: WXR\EventBundle\Entity\TagManager
        arguments: [@doctrine.orm.entity_manager, %wxr_event.tag.class%]
    wxr_event.tag.admin.default:
        class: WXR\EventBundle\Admin\Entity\TagAdmin
        arguments: [ ~, %wxr_event.tag.class%, SonataAdminBundle:CRUD ]
        calls:
            - [ setTranslationDomain, [ %wxr_event.translation_domain% ] ]
        tags:
            -
                name: sonata.admin.disabled
                manager_type: orm
                group: wxr_event
                label: tags
                label_catalogue: %wxr_event.translation_domain%
                label_translator_strategy: sonata.admin.label.strategy.underscore
